### ISSUE TITLE
Error in coef(test.reg)[2, 1] : subscript out of bounds

### ISSUE THREAD

**Issue by wgova** [cran/seer#1]
Can you please implement changes related to `https://github.com/robjhyndman/tsfeatures/commit/108cb72677e11a76b04b83398858f411a18b0edb`

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
